apiVersion: v1
kind: Service
metadata:
  name: kibana-scraper-nodeport
  namespace: elastic
spec:
  type: NodePort
  selector:
    kibana.k8s.elastic.co/name: kibana-scraper
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 30001 # Puerto NodePort especificado